spring.application.name=auth-service-nov2

server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/auth-service-nov-2-db
spring.datasource.username=root
spring.datasource.password=test
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true